name: Test Create Pull Request v5

on:
  push:
    branches:
      - test-create-pull-request-v5

jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Reset main to test branch
        run: |
          git fetch origin test-create-pull-request-v5:test-create-pull-request-v5
          git reset --hard test-create-pull-request-v5

      - name: Import GPG Key
        id: gpg_importer
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          body: ''
          draft: true
          commit-message: Test it
          committer: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          delete-branch: true
          signoff: true
          title: test github action
          token: ${{ secrets.HEDERA_BOT_TOKEN }}
